// -------------- ADD THESE HELPERS INSIDE pages/index.js (inside the Home component scope) --------------

// Create high-res canvas images for each histogram and return dataURLs
async function createHistogramDataURLs(stats) {
  // returns array of {variable, dataUrl}
  const results = []
  for (const s of stats) {
    const vals = (s.rawValues || []).filter(isFinite)
    // canvas size & high-res scale
    const w = 400, h = 120, scale = 2
    const cnv = document.createElement('canvas')
    cnv.width = w * scale
    cnv.height = h * scale
    cnv.style.width = w + 'px'
    cnv.style.height = h + 'px'
    const ctx = cnv.getContext('2d')
    ctx.scale(scale, scale)
    // background
    ctx.fillStyle = '#ffffff'
    ctx.fillRect(0, 0, w, h)
    // draw title
    ctx.fillStyle = '#222'
    ctx.font = '14px sans-serif'
    ctx.fillText(s.variable, 8, 18)
    // histogram bars
    if (vals.length) {
      const bins = 8
      const minv = Math.min(...vals)
      const maxv = Math.max(...vals)
      const counts = new Array(bins).fill(0)
      vals.forEach(x => {
        const idx = Math.min(bins - 1, Math.floor(((x - minv) / (maxv - minv || 1)) * bins))
        counts[idx]++
      })
      const maxc = Math.max(...counts)
      const barW = (w - 20) / bins
      for (let i = 0; i < bins; i++) {
        const bh = maxc ? (counts[i] / maxc) * (h - 50) : 0
        ctx.fillStyle = '#222233'
        ctx.fillRect(10 + i * barW, h - bh - 20, barW - 6, bh)
      }
      // axis line
      ctx.strokeStyle = '#ccc'
      ctx.beginPath()
      ctx.moveTo(8, h - 20)
      ctx.lineTo(w - 8, h - 20)
      ctx.stroke()
    } else {
      ctx.fillStyle = '#999'
      ctx.fillText('No numeric values', 10, 60)
    }
    const dataUrl = cnv.toDataURL('image/png', 0.95)
    results.push({ variable: s.variable, dataUrl })
  }
  return results
}

// Build doc HTML and download as .doc
async function downloadDoc() {
  if (!stats || stats.length === 0) {
    alert('No results to export')
    return
  }
  // get histograms
  const imgs = await createHistogramDataURLs(stats)

  // build table rows as HTML
  const rowsHtml = stats.map(s => {
    const imgObj = imgs.find(x => x.variable === s.variable)
    const imgTag = imgObj ? `<img src="${imgObj.dataUrl}" style="max-width:360px; height:auto; display:block; margin:6px 0;" />` : ''
    return `
      <tr>
        <td style="padding:8px; border:1px solid #ddd;"><strong>${s.variable}</strong></td>
        <td style="padding:8px; border:1px solid #ddd; text-align:right;">${s.mean}</td>
        <td style="padding:8px; border:1px solid #ddd; text-align:right;">${s.sd}</td>
        <td style="padding:8px; border:1px solid #ddd; text-align:right;">${s.maximum}</td>
        <td style="padding:8px; border:1px solid #ddd; text-align:right;">${s.minimum}</td>
        <td style="padding:8px; border:1px solid #ddd; text-align:right;">${s.median}</td>
        <td style="padding:8px; border:1px solid #ddd; text-align:right;">${s.cv}</td>
        <td style="padding:8px; border:1px solid #ddd; text-align:right;">${s.skewness}</td>
        <td style="padding:8px; border:1px solid #ddd; text-align:right;">${s.kurtosis}</td>
        <td style="padding:8px; border:1px solid #ddd; text-align:right;">${s.pctna}</td>
        <td style="padding:8px; border:1px solid #ddd; vertical-align:top;">${imgTag}</td>
      </tr>`
  }).join('')

  const html = `
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Analysis Results</title>
        <style>
          body { font-family: Arial, Helvetica, sans-serif; color: #222; }
          h1 { background:#0b6a13; color:white; padding:10px; }
          table { border-collapse: collapse; width:100%; }
          th { background:#0b6a13; color:white; padding:10px; border:1px solid #ddd; }
        </style>
      </head>
      <body>
        <h1>Summary Statistics</h1>
        <table>
          <thead>
            <tr>
              <th>Variable</th><th>Means</th><th>SD</th><th>Max</th><th>Min</th><th>Median</th><th>CV</th><th>Skew</th><th>Kurt</th><th>%NA</th><th>Histogram</th>
            </tr>
          </thead>
          <tbody>
            ${rowsHtml}
          </tbody>
        </table>
        <p style="font-size:11px;color:#666;">Generated by Stat Summary Webapp — client-side.</p>
      </body>
    </html>
  `

  const blob = new Blob(['\ufeff', html], { type: 'application/msword' }) // BOM + HTML for Word
  saveAs(blob, 'analysis-results.doc')
}
